### ISSUE TITLE
Blank presentation

### ISSUE THREAD

**Issue by drfurtado** [SamGuay/revealjs#3]
`Update`
I can confirm that the problem is related to pandoc. The behavior described below started when I upgraded pandoc from 2.9 to 2.14

Hi @SamGuay,
It was working fine until today. Now, I get a blank page when rendered, even when trying to preview in browser. Any help would be greatly appreciated.

files:

test.Rmd

```
---
title: "Untitled"
---

## R Markdown

This is an R Markdown presentation. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.
```

_output.yaml

```
revealjs::revealjs_presentation:
  self_contained: false
  reveal_plugins: ["chalkboard", "search", "zoom", "notes", "menu"]
  reveal_options:
      chalkboard:
        theme: whiteboard
  theme: sky
  highlight: pygments
  transition: slide
  center: false
  controls: true
  controlsTutorial: true
  disableLayout: true
  incremental: true
```
